FROM ros:melodic-ros-core-bionic

RUN apt update &&\
    apt install -y python-rosdep build-essential git python-pip python3-pip python-virtualenv python-rospkg ros-melodic-rosmon &&\
    sudo rosdep init && rosdep update &&\
    pip3 install pandas

COPY .devcontainer/additional_bashrc.sh /root/.additional_bashrc

RUN cat "/root/.additional_bashrc" >> /root/.bashrc && rm /root/.additional_bashrc