FROM ros:melodic-ros-core-bionic

RUN apt update && apt install -y python-rosdep build-essential git tmux && sudo rosdep init && rosdep update

COPY .devcontainer/.tmux.conf /root/.tmux.conf
COPY .devcontainer/additional_bashrc.sh /root/.additional_bashrc

RUN cat "/root/.additional_bashrc" >> /root/.bashrc && rm /root/.additional_bashrc
